######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 19 16:36:28 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp \
    gotocelldialog.cpp

HEADERS += \
    gotocelldialog.h
