######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 28 17:32:18 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug release
INCLUDEPATH += .

# Input
HEADERS += ticker.h tickerplugin.h
SOURCES += ticker.cpp tickerplugin.cpp
RESOURCES += icons.qrc
